### ISSUE TITLE
DbContext.Database.Migrate() fails when called from second DbContext for the same Database.

### ISSUE THREAD

**Issue by Givko** [dotnet/efcore#20991]
I have the following scenario:

I have two projects(microservices) using one Database(MSSQL), however they have two DbContexts, one for each asp.net core project. Both projects have migration which we apply at runtime we have created an extension method for the IWebHost

```
using System;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace Service.Extensions.WebHost
{
    public static class WebHostExtension
    {
        public static IWebHost MigrateDbContext<TContext>(this IWebHost webHost, Action<TContext, IServiceProvider> seeder) 
            where TContext : DbContext
        {
            using (var scope = webHost.Services.CreateScope())
            {
                var services = scope.ServiceProvider;

                var logger = services.GetRequiredService<ILogger<TContext>>();

                var context = services.GetService<TContext>();

                try
                {
                    logger.LogInformation($"Migrating database associated with context {typeof(TContext).Name}");

                    context.Database.Migrate();

                    seeder(context, services);

                    logger.LogInformation($"Migrated database associated with context {typeof(TContext).Name}");
                }
                catch (Exception ex)
                {
                    logger.LogError(ex, $"An error occurred while migrating the database used on context {typeof(TContext).Name}");
                }
            }

            return webHost;
        }
    }
}
```

Which we call in the Program.cs:

```
public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args)
                .MigrateDbContext<AppDbContext>()
                .Run();
        }

        public static IWebHost CreateHostBuilder(string[] args) =>
             WebHost.CreateDefaultBuilder(args)
                .UseUrls("http://*:8108;") //64295            
                .UseStartup<Startup>()
                .Build();
    }
```
We use it the exact same way in both Program.cs files for both projects.

The problem which we have is the following:

We use docker-compose.yml file to build the docker containers. Everything is fine when we call docker-compose build. When we call docker-compose up everything goes well until the migrations are applied. 
When one of the Program.cs files is executed and the migrations start applying the other project gets an " Error: 18456, Severity: 14, State: 38." error, when trying to apply the migrations from the other context, stating that the credentials are valid but the database is unavailable. After everythinh is up only one of the two migrations has been applied, it just depends on which project has started applying first. Sometimes its one, another time is the other.

One thing that comes to my mind is that the Migrate() method locks the database and that is way when the other method tries to execute its migrations it gets the error. If this is the case could you please tell how can I cope with this issue. We want to apply the migrations at runtime, if possible. And cannot change the app to use one DbContext instead of two.

docker-compose.yml

```
version: '3.4'

services:
  service1:
    container_name: service1
    image: service1
    build:
      context: .
      dockerfile: service1/Dockerfile
    depends_on:
      - .db

  service2:
    container_name: service2
    image: service2     
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: service2/Dockerfile
    depends_on:
      - service1
      - db

  db:
    container_name: db
    image: microsoft/mssql-server-linux:latest
    environment:
      SA_PASSWORD: "password"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "port:port"

```

Connectionstring is 100% correct on both projects as sometimes the migrations from accountsservice get applied and other times the migrations from bankservice are applied.

I forgot to say that running docker-compose up a second time applies the migrations from the project which did not apply its migrations due to the  "Error: 18456, Severity: 14, State: 38." error.

### Further technical details

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .net core 3.1 and .net core 2.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.3
