### ISSUE TITLE
Ad-hoc type with property that looks like collection navigation does not fail model validation

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#30056]
Instead, it is just ignored. Reference navigations will cause validation to fail.

Code:

```C#
public class Blog
{
    public string? Name { get; set; }
    public virtual List<Post> Posts { get; } = new();
}

public class Post
{
    public string? Title { get; set; }
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Data Source=(LocalDb)\MSSQLLocalDB;Database=AllTogetherNow")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>().HasNoKey();
        modelBuilder.Entity<Post>().HasNoKey();
    }
}

public class Program
{
    public static async Task Main()
    {
        using (var context = new SomeDbContext())
        {
             await context.Database.EnsureDeletedAsync();
             await context.Database.EnsureCreatedAsync();

             await context.SaveChangesAsync();
        }
    }
}
```

Model:

```
Model: 
  EntityType: Blog Keyless
    Properties: 
      Name (string)
  EntityType: Post Keyless
    Properties: 
      Title (string)
```
