### ISSUE TITLE
Azure Pipeline, dotnet ef migrations bundle, fails when 'assemblyVersion' defined

### ISSUE THREAD

**Issue by Appelg** [dotnet/efcore#30879]
## Ask a question
I stumbled upon an error that took me ages to figure out and I still don't understand why it happens.

I have a simple pipeline for debugging where all basically all I do is the following:
`migrations bundle --verbose --force --self-contained --target-runtime win-x64 -o $(Build.ArtifactStagingDirectory)\efbundle.exe`

If I have a `assemblyVersion` YML-variable defined, and it doesn't conform to the` x.x.x.x `form, the build fails.
(That might be bad practice, but that was what happend in the production pipeline which consists of a lot of templates and  variable-groups, which was why it took me so long to figure out).

**Edit:** Turns out that our assemblyversion is correct semver, it was just an unfortunate variablename for something else!(!!)
`AssemblyProduct: $(assemblyVersion)`

What I don't understand is why this variable is even used? It's not used anywhere in my YAML-file, so there has to be som magic in either the `DotNetCOreCLI@2` or `dotnet `or `dotnet-ef `tool, or some of the build-tools, that finds out that the YAML-variable `assemblyVersion` is set, and then it uses that string to be used when it autogenerates the `csproj `and/or `efbundle.AssemblyInfo.cs` file?

**I'm just curious about how this happens? I have tried to look at / search the source code for several of the components but I still have no clue.** 

Thanks!

### Include your code

```
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-2022

variables:
- name: assemblyVersion
  value: 'foo_bar_baz'

steps:

- task: DotNetCoreCLI@2
  displayName: New Manifest for tool installation
  inputs:
    command: custom
    custom: 'new '
    arguments: tool-manifest

- task: DotNetCoreCLI@2
  displayName: Install EF Tool
  inputs:
    command: custom
    custom: 'tool '
    arguments: install --global dotnet-ef --version 7.0.4

- task: DotNetCoreCLI@2
  displayName: "Create EF Core migrations efbundle.exe"
  inputs:
    command: 'custom'
    custom: 'ef'
    arguments:  'migrations bundle --verbose --force --self-contained --target-runtime win-x64 -o $(Build.ArtifactStagingDirectory)\efbundle.exe'
    workingDirectory: 'EfBundleTest'
```

### Include stack traces
Ok, so here's the problem.
(1) Define a YML-variable `assemblyVersion` and give it a none semver name.
(2) Nowhere in the tasks is this above variable (1) used as an argument
(3) & (4) The dotnet publish action for the automatic-generated "efbundle.csproj" seems to use this `assemblyVersion` variable and fails.

If I remove the variable from the YML-file, (1) in the image,  or change it to somthing like` 1.3.3.7`, everything works fine.

![image](https://github.com/dotnet/efcore/assets/50763504/95e7f25b-b230-4540-a7e3-2316486e99a7)

### Include provider and version information

Dotnet-ef: 7.0.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET 6. 0
Operating system: Azure Pipelines, windows-2022 image
