### ISSUE TITLE
Environment based connection string with Docker support and Code-First Migration

### ISSUE THREAD

**Issue by dapalmi** [dotnet/efcore#8855]
I have a ASP.NET Core app with Docker support and following service configuration in the `Startup.cs`:

```
        string connectionString = Environment.GetEnvironmentVariable("ORACLE_CONNECTION_STRING");
        services.AddDbContext<BloggingContext>(options => options.UseOracle(connectionString)); 
```

I set the connection string in the `docker-compose.override.yml`:
```

version: '2'
services:
  continuouseverything:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ORACLE_CONNECTION_STRING=Server=(DESCRIPTION = (ADDRESS = (PROTOCOL=TCP) (HOST=LOCALHOST) (PORT=1521)) (CONNECT_DATA= (SERVER=DEDICATED) (SERVICE_NAME=xe.oracle.docker))); direct=true; User Id=system; Password=oracle; Unicode=true
    ports:
      - "80"
```

It works fine when I just start the app via Docker. And in Debugger I can see that the `connectionString `variable got the right connection String.

But when I try to run `Add-Migration InitialCreate` I get an `ArgumentNullException `in the `Startup.cs `when `services.AddDbContext()` is called because the `connectionString `variable is null.

How do I accomplish this, that the `EnvironmentVariable `is set like defined in the `docker-compose `file?

EF Core version:  Microsoft.EntityFrameworkCore.Tools (1.1.1)
Database Provider: Devart.Data.Oracle.EFCore (9.4.280)
IDE: Visual Studio 2017
